### ISSUE TITLE
Application fails when creating a new vacancy in admin

### ISSUE THREAD

**Issue by anxolerd** [uaprom-summer-2015/Meowth#154]
## Description
When user tries to create a new vacancy, an application fails with error. However it is still posible to edit existing vacancy.

## STR
1. Launch application
2. Go to `/admin/vacancy/` to create a new vacancy
3. Create a new vacancy and click to save vacancies

## Expected result
Vacancy created or user receives a message why such vacancy cannot be created

## Actual result
Application fails with the following stack trace:
```pytb
Traceback (most recent call last):
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Meowth/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Meowth/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Meowth/env/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Meowth/project/auth/decorators.py", line 20, in wrapped
    return func(*args, **kwargs)
  File "/Meowth/env/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Meowth/env/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/Meowth/project/admin/utils.py", line 56, in post
    self.model.bl.create(form.data)
  File "/Meowth/project/bl/utils.py", line 52, in create
    self.save()
  File "/Meowth/project/bl/utils.py", line 63, in save
    db.session.add(self.model)
  File "/Meowth/env/lib/python3.4/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Meowth/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 1575, in add
    raise exc.UnmappedInstanceError(instance)
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'flask_sqlalchemy._BoundDeclarativeMeta' is not mapped; was a class (project.models.Vacancy) supplied where an instance was required?
```

### Screenshot 1. Creating a new vacancy
![Creating a new vacancy](https://cloud.githubusercontent.com/assets/6533582/9379713/c5fca25c-4733-11e5-86ea-80763cca3948.png)

### Screenshot 2. App fails with traceback
![Fail with a traceback](https://cloud.githubusercontent.com/assets/6533582/9379747/11811654-4734-11e5-8dc0-c2e326310492.png)

**Comment by anxolerd** [comment]
**UPD** This happens on other models too
