### ISSUE TITLE
Alembic migrations do not work

### ISSUE THREAD

**Issue by anxolerd** [uaprom-summer-2015/Meowth#25]
Alembic migrations fail because of lack of project in their pathes

```
Traceback (most recent call last):
  File "/home/a.kovalchuk/workspace/Meowth/env/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.7.6', 'console_scripts', 'alembic')()
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/config.py", line 439, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/config.py", line 433, in main
    self.run_cmd(cfg, options)
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/config.py", line 416, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/command.py", line 165, in upgrade
    script.run_env()
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/script.py", line 390, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/util.py", line 243, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1591, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "project/alembic/env.py", line 75, in <module>
    run_migrations_online()
  File "project/alembic/env.py", line 70, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/environment.py", line 738, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/a.kovalchuk/workspace/Meowth/env/lib/python3.4/site-packages/alembic/migration.py", line 309, in run_migrations
    step.migration_fn(**kw)
  File "/home/a.kovalchuk/workspace/Meowth/project/alembic/versions/20ee934fbbd_add_entities.py", line 33, in upgrade
    sa.Column('role', project.lib.orm.types.TypeEnum(), nullable=True),
NameError: name 'project' is not defined
```

**Comment by anxolerd** [comment]
Temporary solution:

Edit migrations manually if needed.

TODO: find solutions to automate this

**Comment by Cybran111** [comment]
Fixed?
